name: Test
on: 
  workflow_dispatch:
jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: test 
        run: node script/getData.js test
        env: 
          NOTION_CAREER_DATABASE_ID: ${{ secrets.NOTION_CAREER_DATABASE_ID }}
          NOTION_CAREER_PROJECT_DATABASE_ID: ${{ secrets.NOTION_CAREER_PROJECT_DATABASE_ID }}
          NOTION_CERTIFICATE_DATABASE_ID: ${{ secrets.NOTION_CERTIFICATE_DATABASE_ID }}
          NOTION_CODING_PRACITCE_CATEGORIES_DATABASE_ID: ${{ secrets.NOTION_CODING_PRACITCE_CATEGORIES_DATABASE_ID }}
          NOTION_CODING_PRACTICE_DATABASE_ID: ${{ secrets.NOTION_CODING_PRACTICE_DATABASE_ID }}
          NOTION_CODING_PRACTICE_LOG_DATABASE_ID: ${{ secrets.NOTION_CODING_PRACTICE_LOG_DATABASE_ID }}
          NOTION_DETAILED_PLAN_DATABASE_ID: ${{ secrets.NOTION_DETAILED_PLAN_DATABASE_ID }}
          NOTION_EXPERIENCE_DETAIL_DATABASE_ID: ${{ secrets.NOTION_EXPERIENCE_DETAIL_DATABASE_ID }}
          NOTION_EXPERIENCE_PRACTICE_DATABASE_ID: ${{ secrets.NOTION_EXPERIENCE_PRACTICE_DATABASE_ID }}
          NOTION_EXPERIENCE_PROJECT_DATABASE_ID: ${{ secrets.NOTION_EXPERIENCE_PROJECT_DATABASE_ID }}
          NOTION_INTEGRATION_SECRET: ${{ secrets.NOTION_INTEGRATION_SECRET }}
          NOTION_PLAN_DATABASE_ID: ${{ secrets.NOTION_PLAN_DATABASE_ID }}
          NOTION_SKILLS_DATABASE_ID: ${{ secrets.NOTION_SKILLS_DATABASE_ID }}
