name: Update Activities
on: 
  workflow_dispatch:
  schedule:
    - cron: '1 0 1 * *'

permissions:
  contents: write
  
jobs:
  fetch-data:
    uses: ./.github/workflows/fetchData.yml  
    with:
      data: "activities"  
    secrets:
      NOTION_CAREER_DATABASE_ID: ${{ secrets.NOTION_CAREER_DATABASE_ID }}
      NOTION_CAREER_PROJECT_DATABASE_ID: ${{ secrets.NOTION_CAREER_PROJECT_DATABASE_ID }}
      NOTION_CERTIFICATE_DATABASE_ID: ${{ secrets.NOTION_CERTIFICATE_DATABASE_ID }}
      NOTION_CODING_PRACITCE_CATEGORIES_DATABASE_ID: ${{ secrets.NOTION_CODING_PRACITCE_CATEGORIES_DATABASE_ID }}
      NOTION_CODING_PRACTICE_DATABASE_ID: ${{ secrets.NOTION_CODING_PRACTICE_DATABASE_ID }}
      NOTION_CODING_PRACTICE_LOG_DATABASE_ID: ${{ secrets.NOTION_CODING_PRACTICE_LOG_DATABASE_ID }}
      NOTION_DETAILED_PLAN_DATABASE_ID: ${{ secrets.NOTION_DETAILED_PLAN_DATABASE_ID }}
      NOTION_EXPERIENCE_DETAIL_DATABASE_ID: ${{ secrets.NOTION_EXPERIENCE_DETAIL_DATABASE_ID }}
      NOTION_EXPERIENCE_PRACTICE_DATABASE_ID: ${{ secrets.NOTION_EXPERIENCE_PRACTICE_DATABASE_ID }}
      NOTION_EXPERIENCE_PROJECT_DATABASE_ID: ${{ secrets.NOTION_EXPERIENCE_PROJECT_DATABASE_ID }}
      NOTION_INTEGRATION_SECRET: ${{ secrets.NOTION_INTEGRATION_SECRET }}
      NOTION_PLAN_DATABASE_ID: ${{ secrets.NOTION_PLAN_DATABASE_ID }}
      NOTION_SKILLS_DATABASE_ID: ${{ secrets.NOTION_SKILLS_DATABASE_ID }}